# Generated by Django 4.2.13 on 2024-05-19 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/pdf/'),
            preserve_default=False,
        ),
    ]
