# Generated by Django 4.2.13 on 2024-05-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_date_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_shipped',
        ),
    ]
